import assert from "node:assert/strict";
import fs from "node:fs";
import { fileURLToPath } from "node:url";

const workflow = JSON.parse(fs.readFileSync(fileURLToPath(new URL("../../../n8n/workflows/INT-HCTI-editorial-render-bridge-dev.workflow.json", import.meta.url)), "utf8"));
const byName = Object.fromEntries(workflow.nodes.map((node) => [node.name, node]));
const next = (source, output = 0) => (workflow.connections[source]?.main?.[output] ?? []).map((edge) => edge.node);

assert.equal(workflow.active, false);
assert.equal(workflow.nodes.length, 27);
assert.equal(workflow.nodes.filter((node) => node.type === "n8n-nodes-base.manualTrigger").length, 1);
assert.equal(workflow.nodes.filter((node) => node.type === "n8n-nodes-base.googleDrive").length, 8);
assert.equal(workflow.nodes.filter((node) => node.name === "HCTI Render — Single Attempt").length, 1);
assert.equal(byName["HCTI Render — Single Attempt"].retryOnFail, false);
assert.equal(byName["Download HCTI rendered PNG"].retryOnFail, false);
assert.equal(byName["Verify private assets and build locked batch"].parameters.jsCode.includes('"transport_enabled":false'), true);
assert.equal(byName["Verify private assets and build locked batch"].parameters.jsCode.includes('"selected_output_ids":["carousel-04"]'), true);
assert.deepEqual(next("Transport enabled?", 0), ["Build pre-transport evidence row"]);
assert.deepEqual(next("Transport enabled?", 1), ["Build workflow_runs terminal row"]);
assert.deepEqual(next("Build pre-transport evidence row"), ["Persist pre-transport evidence"]);
assert.deepEqual(next("Persist pre-transport evidence"), ["Restore verified HCTI request"]);
assert.deepEqual(next("Restore verified HCTI request"), ["HCTI Render — Single Attempt"]);
assert.deepEqual(next("Normalize HCTI batch result"), ["Build transport-settled evidence row"]);
assert.deepEqual(next("Build transport-settled evidence row"), ["Persist transport-settled evidence"]);
assert.deepEqual(next("Persist transport-settled evidence"), ["Restore normalized HCTI result"]);
assert.deepEqual(next("Restore normalized HCTI result"), ["Submission returned render URL?"]);
assert.deepEqual(next("Submission returned render URL?", 0), ["Download HCTI rendered PNG"]);
assert.deepEqual(next("Submission returned render URL?", 1), ["Build workflow_runs terminal row"]);
assert.equal(workflow.settings.saveManualExecutions, false);
assert.equal(workflow.settings.saveDataSuccessExecution, "none");
assert.equal(workflow.settings.saveDataErrorExecution, "none");
assert.equal(workflow.settings.saveExecutionProgress, false);
assert.equal(workflow.meta.terminal_postflight_enabled, true);
assert.equal(workflow.meta.browser_layout_verified, false);
assert.equal(workflow.meta.maximum_hcti_calls_per_execution, 1);
assert.equal(byName["Verify private assets and build locked batch"].parameters.jsCode.includes("TERMINAL_POSTFLIGHT_REQUIRED"), true);
assert.equal(byName["Verify private assets and build locked batch"].parameters.jsCode.includes("BROWSER_LAYOUT_NOT_VERIFIED"), true);
assert.equal(byName["Build pre-transport evidence row"].parameters.jsCode.includes("request_sha256"), true);
assert.equal(byName["Build transport-settled evidence row"].parameters.jsCode.includes("raw_response_persisted:false"), true);
assert.equal(workflow.nodes.some((node) => Object.values(node.credentials ?? {}).some((credential) => "id" in credential)), false, "Reusable credential references must not contain immutable credential IDs.");
assert.equal(/data:image\/(?:png|jpeg);base64,[A-Za-z0-9+/]/.test(JSON.stringify(workflow)), false);
assert.equal(JSON.stringify(workflow).includes("INT-AUT-014"), false);
console.log("private delivery workflow tests: 32 passed");
