import test from "node:test";
import assert from "node:assert/strict";
import {loadControlledWorkflow,validateControlledWorkflow,compareSemanticFingerprint,WORKFLOW_NAME,VIDEO_ID,CREDENTIAL_NAME} from "../validate-int-tst-013-dolly-transcriptapi-controlled-test.mjs";

const workflow=loadControlledWorkflow();
test("controlled workflow is inactive and fixed to the approved Dolly source",()=>{assert.equal(workflow.name,WORKFLOW_NAME);assert.equal(workflow.active,false);assert.equal(workflow.meta.authorized_video_id,VIDEO_ID);assert.equal(workflow.meta.approval_status,"controlled_test_authorized");assert.equal(workflow.meta.authorization_id,"AUT-013-DOLLY-001");});
test("controlled authorization gate is exact and precedes the HTTP node",()=>{const gate=workflow.nodes.find(n=>n.name==="Controlled-test authorization gate");assert.match(gate.parameters.jsCode,/CONTROLLED_TEST_AUTHORIZATION_INVALID/);assert.equal(workflow.connections[gate.name].main[0][0].node,"TranscriptAPI single request (approval required)");});
test("credential, URL and video ID are not input-controlled",()=>{const http=workflow.nodes.find(n=>n.type==="n8n-nodes-base.httpRequest");assert.equal(http.credentials.httpHeaderAuth.name,CREDENTIAL_NAME);assert.equal(http.parameters.url,"https://api.transcriptapi.com/v1/transcript");assert.match(http.parameters.jsonBody,/PIa6Vot1XcM/);assert.doesNotMatch(JSON.stringify(workflow),/input_video|input_url|input_credential|process\.env/i);});
test("one attempt and no retry capability are structural",()=>{assert.equal(workflow.meta.provider_call_budget,1);assert.equal(workflow.meta.maximum_real_transport_attempts,1);assert.equal(workflow.meta.automatic_retries,0);assert.doesNotMatch(JSON.stringify(workflow),/retryOnFail|maxTries|setTimeout|setInterval/i);});
test("only Manual Trigger and no ScrapeCreators path exist",()=>{assert.equal(workflow.nodes.filter(n=>n.type.includes("Trigger")).length,1);assert.equal(workflow.nodes.filter(n=>n.type==="n8n-nodes-base.manualTrigger").length,1);assert.doesNotMatch(JSON.stringify(workflow),/ScrapeCreators|scrapecreators|webhook|scheduleTrigger|wait/i);});
test("cache hit and prior usage are before transport, terminal output is sanitized",()=>{const names=workflow.nodes.map(n=>n.name);assert.ok(names.indexOf("Exact media cache lookup")<names.indexOf("TranscriptAPI single request (approval required)"));assert.ok(names.indexOf("Exact provider_usage lookup")<names.indexOf("TranscriptAPI single request (approval required)"));const terminal=workflow.nodes.find(n=>n.name==="Persist and exit").parameters.jsCode;assert.match(terminal,/persist_and_exit/);assert.doesNotMatch(JSON.stringify(workflow),/raw transcript text|response_body|request_headers/i);});
test("canonical Data Table reads and durable inserts are present",()=>{const tables=workflow.nodes.filter(n=>n.type==="n8n-nodes-base.dataTable");assert.equal(tables.length,6);const ids=tables.map(n=>n.parameters.dataTableId?.value);assert.ok(ids.includes("MtW6eqUyU7oiPRB0"));assert.ok(ids.includes("WFeE982gMt0XfiIm"));assert.ok(ids.includes("ZdOyJqa5ffTkwUSV"));assert.equal(workflow.connections["Cache hit decision"].main[0][0].node,"workflow_runs terminal state");assert.equal(workflow.connections["Cache hit decision"].main[1][0].node,"Exact provider_usage lookup");});
test("validator rejects activation, video override, credential override and forbidden capability",()=>{for(const mutate of [w=>{w.active=true;},w=>{w.meta.authorized_video_id="other";},w=>{w.nodes.find(n=>n.type==="n8n-nodes-base.httpRequest").credentials.httpHeaderAuth.name="other";},w=>{w.nodes.push({name:"Webhook",type:"n8n-nodes-base.webhook"});}]){const copy=structuredClone(workflow);mutate(copy);assert.throws(()=>validateControlledWorkflow(copy));}});
test("semantic fingerprint ignores n8n-managed metadata but retains security semantics",()=>{const deployed=structuredClone(workflow);delete deployed.meta;deployed.versionId="instance-version";deployed.createdAt="managed";deployed.updatedAt="managed";deployed.triggerCount=0;for(const node of deployed.nodes){delete node.id;delete node.position;if(node.credentials?.httpHeaderAuth)node.credentials.httpHeaderAuth.id="immutable-runtime-id";}assert.equal(compareSemanticFingerprint(workflow,deployed).equal,true);});
